apiVersion: apps/v1
kind: Deployment
metadata:
  name: cuda-test
  labels:
    app: cuda-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cuda-test
  template:
    metadata:
      labels:
        app: cuda-test
    spec:
      containers:
      - name: cuda-test-main
        image: "k8s.gcr.io/cuda-vector-add:v0.1"
        command: ["bash", "-c", "for (( c=1; c<=50000; c++ )); do ./vectorAdd; done"]
        resources:
          limits:
            nvidia.com/gpu: 1