prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
    - job_name: gpu-metrics
      scrape_interval: 1s
      metrics_path: /metrics
      scheme: http
      kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
          - default
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_node_name]
        action: replace
        target_label: node

# additionalPrometheusRulesMap:
#   gpu-rules:
#     groups:
#     - name: gpu-rule-group
#       rules:
#       - record: deployment_namespace:dcgm_gpu_utilization:avg                            
#         expr: avg(dcgm_gpu_utilization)
#         labels:
#           namespace: "default"
#           deployment: "cuda-test"